# Generated by Django 5.2.1 on 2025-05-21 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
                ('prijmeni', models.CharField(max_length=100)),
                ('adresa', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('popis', models.TextField()),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('skladova_zasoba', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
                ('prijmeni', models.CharField(max_length=100)),
                ('specializace', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('popis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('znacka', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('rok_vyroby', models.IntegerField()),
                ('vin', models.CharField(max_length=50)),
                ('spz', models.CharField(max_length=20)),
                ('majitel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.owner')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_servisu', models.DateField()),
                ('typ_servisu', models.CharField(max_length=100)),
                ('popis', models.TextField()),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.car')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.technician')),
                ('worktype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.worktype')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnozstvi', models.IntegerField()),
                ('aktualni_cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicerecord')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sparepart')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_servisu', models.DateField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('popis', models.TextField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.car')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.technician')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datum_od', models.DateField()),
                ('datum_do', models.DateField()),
                ('worktype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.worktype')),
            ],
        ),
    ]
